export const mockUsers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2023-11-10",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2023-10-25",
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2023-11-08",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-11-05",
  },
  {
    id: 5,
    name: "Michael Wilson",
    email: "michael@example.com",
    role: "Editor",
    status: "Active",
    lastLogin: "2023-11-09",
  },
  {
    id: 6,
    name: "Sarah Brown",
    email: "sarah@example.com",
    role: "User",
    status: "Inactive",
    lastLogin: "2023-10-15",
  },
  {
    id: 7,
    name: "David Miller",
    email: "david@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2023-11-07",
  },
  {
    id: 8,
    name: "Lisa Anderson",
    email: "lisa@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-11-01",
  },
  {
    id: 9,
    name: "Thomas Taylor",
    email: "thomas@example.com",
    role: "Editor",
    status: "Inactive",
    lastLogin: "2023-10-28",
  },
  {
    id: 10,
    name: "Jessica Wilson",
    email: "jessica@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-11-03",
  },
  {
    id: 11,
    name: "Daniel Martin",
    email: "daniel@example.com",
    role: "Admin",
    status: "Active",
    lastLogin: "2023-11-06",
  },
  {
    id: 12,
    name: "Jennifer Lee",
    email: "jennifer@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-11-02",
  },
  {
    id: 13,
    name: "James Harris",
    email: "james@example.com",
    role: "Editor",
    status: "Inactive",
    lastLogin: "2023-10-20",
  },
  {
    id: 14,
    name: "Amanda Clark",
    email: "amanda@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-11-04",
  },
  {
    id: 15,
    name: "Kevin Wright",
    email: "kevin@example.com",
    role: "User",
    status: "Active",
    lastLogin: "2023-11-01",
  },
]; 